const socketConstants = {
  S_INITIALIZE: 'S_INITIALIZE',
  C_INITIALIZE: 'C_INITIALIZE',
  S_GAME_UPDATE: 'S_GAME_UPDATE',
  C_MOVE: 'C_MOVE',
  S_MOVE_CONFIRMATION: 'S_MOVE_CONFIRMATION',
  S_PING_REQUEST: 'S_PING_REQUEST',
  C_PING_RESPONSE: 'C_PING_RESPONSE',
  S_PING_NOTIFICATION: 'S_PING_NOTIFICATION',
  C_COLLISION_EVENT: 'C_COLLISION_EVENT',
};

module.exports = socketConstants;
